/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef simple01_CONSTANTS_H
#define simple01_CONSTANTS_H

#include "simple01_types.h"



class simple01Constants {
 public:
  simple01Constants();

};

extern const simple01Constants g_simple01_constants;



#endif
