/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "simple01_constants.h"



const simple01Constants g_simple01_constants;

simple01Constants::simple01Constants() {
}



